/* Standalone browser simulation only. No server, authentication boundary or real money. */
const offlineKey='oriental24-html-demo-v1';
const ocopy=x=>JSON.parse(JSON.stringify(x));
let localDemo=ocopy(OFFLINE_SEED),localUser=null,localPersistence=false;
try { const old=localStorage.getItem(offlineKey);if(old){const parsed=JSON.parse(old);if(parsed.version===1)localDemo=parsed;}localStorage.setItem(offlineKey,JSON.stringify(localDemo));localPersistence=true; }catch{}
localDemo.users.forEach(u=>{u.client_type=u.client_type||'vendeur'});
localDemo.client_type_audit=localDemo.client_type_audit||[];
localDemo.announcements=localDemo.announcements||ocopy(OFFLINE_SEED.announcements||[]);
localDemo.announcement_audit=localDemo.announcement_audit||[];
localDemo.followup_reasons=localDemo.followup_reasons||ocopy(OFFLINE_SEED.followup_reasons||[]);
const onow=()=>new Date().toISOString();
const oid=rows=>Math.max(0,...rows.map(r=>r.id||0))+1;
const find=(rows,id)=>{const r=rows.find(r=>r.id===Number(id));if(!r)throw Error('Élément introuvable dans cette démo.');return r};
const ouser=id=>localDemo.users.find(u=>u.id===Number(id))||{};
const oscope=(r,key='client_id')=>localUser.role==='admin'||r[key]===localUser.id;
const oclosed=p=>['Livré','Retourné','Refusé'].includes(p.status);
function requireAdmin(){if(localUser?.role!=='admin')throw Error('Action réservée au mode Admin de la démo.')}
function opersist(){try{localStorage.setItem(offlineKey,JSON.stringify(localDemo));}catch{localPersistence=false}}
function ocent(value){const v=String(value??'').replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(v)||Number(v)>1e9)throw Error('Montant positif ou nul, deux décimales maximum.');return Math.round(Number(v)*100)}
function oclientType(d,role){const kind=d.client_type??'vendeur';if(!clientTypeOptions.some(([k])=>k===kind)||role!=='client'&&kind!=='vendeur')throw Error('Choisissez un type de client valide.');return kind}
function otracking(client,value){
 if(client.role!=='client'||!client.active)throw Error('Client actif requis.');
 if(client.client_type==='societe_livraison'){
  if(typeof value!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._/\-]{0,79}$/.test(value.trim()))throw Error('Tracking obligatoire : 1 à 80 caractères lettres, chiffres, . - _ / ; début alphanumérique.');
  const tracking=value.trim();if(localDemo.parcels.some(p=>p.tracking.toUpperCase()===tracking.toUpperCase()&&p.client_id===client.id))throw Error('Ce tracking est déjà utilisé pour cette société. Aucun colis ajouté.');return tracking;
 }
 if(value!==undefined&&value!==null&&value!=='')throw Error('Vendeur : tracking ORIENTAL24 automatique.');
 let tracking;do{tracking='O24-'+financeKey().slice(0,10).toUpperCase()}while(localDemo.parcels.some(p=>p.tracking.toUpperCase()===tracking));return tracking;
}
function oparcels(){return localDemo.parcels.filter(p=>oscope(p,localUser.role==='livreur'?'driver_id':'client_id')&&(localUser.role!=='livreur'||(!oreturned(p)&&!opaidParcel(p)))).map(p=>({...p,driver_returned:oreturned(p),reason_label:localDemo.followup_reasons.find(r=>r.code===p.reason_code)?.label||null,city:localDemo.cities.find(c=>c.id===p.city_id)?.name||'',client:ouser(p.client_id).name,company:ouser(p.client_id).company,driver:oreturned(p)?null:ouser(p.driver_id).name||null,driver_phone:oreturned(p)?null:ouser(p.driver_id).phone||null,driver_active:oreturned(p)?null:ouser(p.driver_id).active??null,support_name:null,support_phone:null,financial_locked:localDemo.lines.some(l=>l.parcel_id===p.id&&l.active)}))}
function oevent(p,note){localDemo.events.unshift({id:oid(localDemo.events),parcel_id:p.id,status:p.status,note,actor:localUser.name,created_at:onow()})}
function osummary(s){const tx=localDemo.transactions.filter(t=>t.statement_id===s.id&&!t.voided_at);const sum=kind=>tx.filter(t=>t.kind===kind).reduce((a,t)=>a+t.amount_cents,0);const cash=sum('cash'),commission=sum('commission');const cr=s.cancelled_at?0:s.cash_due_cents-cash,rr=s.cancelled_at?0:s.commission_due_cents-commission;return {...s,reference:'DRV-'+String(s.id).padStart(6,'0'),cash_received_cents:cash,commission_paid_cents:commission,cash_remaining_cents:cr,commission_remaining_cents:rr,status:s.cancelled_at?'Annulé':!cr&&!rr?'Soldé':cash+commission?'Partiel':'À régler'}}
function oaudit(did,sid,action,details){localDemo.audit.unshift({id:oid(localDemo.audit),driver_id:did,statement_id:sid,actor_name:localUser.name,action,details:ocopy(details),created_at:onow()})}
function opreview(d){const dr=find(localDemo.users,d.driver_id),t=localDemo.terms[dr.id];if(!t)throw Error('Configurez le barème du livreur avant de créer un relevé.');if(d.period_from&&d.period_to&&d.period_from>d.period_to)throw Error('Période invalide.');const lines=oparcels().filter(p=>p.driver_id===dr.id&&oclosed(p)&&!p.financial_locked&&(!d.period_from||p.updated_at.slice(0,10)>=d.period_from)&&(!d.period_to||p.updated_at.slice(0,10)<=d.period_to)).map(p=>{const override=t.overrides.find(o=>o.city_id===p.city_id),rate=override||t;return {parcel_id:p.id,tracking:p.tracking,city:p.city,status:p.status,cod_cents:p.status==='Livré'?ocent(p.amount):0,commission_cents:rate[{Livré:'delivered_cents',Retourné:'returned_cents',Refusé:'refused_cents'}[p.status]],rate_source:override?'Ville':'Défaut livreur',closed_at:p.updated_at}});if(!lines.length)throw Error('Aucun colis clôturé non rapproché pour cette période.');if(lines.length>500)throw Error('Limite de 500 colis. Réduisez la période.');const cod=lines.reduce((n,p)=>n+p.cod_cents,0),com=lines.reduce((n,p)=>n+p.commission_cents,0),ret=t.mode==='net'?Math.min(cod,com):0;return {driver_id:dr.id,driver_name:dr.name,driver_email:dr.email,mode:t.mode,revision:t.revision,period_from:d.period_from||'',period_to:d.period_to||'',parcel_count:lines.length,cod_cents:cod,commission_cents:com,retained_cents:ret,cash_due_cents:cod-ret,commission_due_cents:com-ret,lines,print_snapshot:{version:1,issuer:ocopy(oinvoiceProfile()),driver:{phone:dr.phone,driver_address:dr.driver_address||'',city:localDemo.cities.find(c=>c.id===dr.driver_city_id)?.name||null},parcels:lines.map(l=>{const p=find(localDemo.parcels,l.parcel_id);return {parcel_id:p.id,phone:p.phone,amount:String(p.amount)}})}}}
function oinvoiceProfile(){return localDemo.invoice_profile||{revision:0,...Object.fromEntries(invoiceProfileFields.map(([k])=>[k,'']))}}
function ofinance(url,method,d){
 const path=url.split('/').slice(2),part=path[0],id=Number(path[1]);
 if(!['admin','livreur'].includes(localUser.role))throw Error('Cette rubrique est réservée à Admin / Livreur.');
 if(method!=='GET')requireAdmin();
 if(part==='invoice-profile'){requireAdmin();const old=oinvoiceProfile();if(method==='GET')return ocopy(old);if(method!=='PUT')throw Error('Méthode non disponible.');if(Object.keys(d).sort().join(',')!==[...invoiceProfileFields.map(([k])=>k),'revision'].sort().join(',')||!Number.isInteger(d.revision)||d.revision<0)throw Error('Champs invalides.');if(d.revision!==old.revision)throw Error('Coordonnées modifiées. Rechargez le formulaire.');const next={revision:old.revision+1};for(const [k,label,max] of invoiceProfileFields){if(typeof d[k]!=='string'||d[k].trim().length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(d[k]))throw Error('Valeur invalide : '+label);next[k]=d[k].trim()}if(next.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.email))throw Error('E-mail invalide.');localDemo.invoice_profile=next;return {ok:true,revision:next.revision}}
 const scoped=()=>localDemo.statements.filter(s=>oscope(s,'driver_id'));
 if(!part){const statements=scoped().map(osummary).reverse(),active=statements.filter(s=>!s.cancelled_at);return {statements,summary:Object.fromEntries(['cod_cents','commission_cents','retained_cents','cash_remaining_cents','commission_remaining_cents'].map(k=>[k,active.reduce((a,s)=>a+s[k],0)])),transactions:localDemo.transactions.filter(t=>scoped().some(s=>s.id===t.statement_id)).map(t=>({...t,driver_name:find(localDemo.statements,t.statement_id).driver_name})).reverse()}}
 if(part==='terms'){
  if(!path[1])return localDemo.users.filter(u=>u.role==='livreur'&&oscope(u,'id')).map(u=>({...u,terms:localDemo.terms[u.id]||null}));
  if(localUser.role==='livreur'&&id!==localUser.id)throw Error('Barème introuvable.');
  if(path[2]==='history')return localDemo.audit.filter(a=>a.driver_id===id&&!a.statement_id);
  if(method==='PUT'){const dr=find(localDemo.users,id),old=localDemo.terms[id];if(dr.role!=='livreur')throw Error('Livreur invalide.');if((old?.revision||0)!==d.revision)throw Error('Rechargez le barème.');if(!['net','gross'].includes(d.mode))throw Error('Choisissez une méthode.');const seen=new Set();const rate=r=>{const v={delivered_cents:ocent(r.delivered),returned_cents:ocent(r.returned),refused_cents:ocent(r.refused)};if(Object.values(v).some(x=>x>1e6))throw Error('Maximum 10 000 MAD par commission.');return v};const overrides=d.overrides.map(r=>{const city=find(localDemo.cities,r.city_id);if(seen.has(city.id))throw Error('Ville répétée.');seen.add(city.id);return {...rate(r),city_id:city.id,city:city.name}});const t={driver_id:id,mode:d.mode,...rate(d),revision:d.revision+1,overrides};localDemo.terms[id]=t;oaudit(id,null,'Barème enregistré',{before:old||null,after:t});return {revision:t.revision}}
 }
 if(part==='preview'){
  if(!path[1]){const snapshot=opreview(d),token=financeKey();localDemo.previews[token]={snapshot,input:ocopy(d),created:Date.now()};return {token,...snapshot}}
  const draft=localDemo.previews[path[1]];if(!draft)throw Error('Aperçu introuvable.');if(draft.sid)return {statement_id:draft.sid,already_created:true};if(Date.now()-draft.created>1800000)throw Error('Aperçu expiré.');const p=opreview(draft.input);if(JSON.stringify(p)!==JSON.stringify(draft.snapshot))throw Error('Données modifiées. Recréez un aperçu.');const sid=oid(localDemo.statements);localDemo.statements.push({...p,lines:undefined,id:sid,created_at:onow(),cancelled_at:null});p.lines.forEach(l=>{localDemo.lines.push({...l,id:oid(localDemo.lines),statement_id:sid,active:1});oevent(find(localDemo.parcels,l.parcel_id),'Relevé livreur créé — simulation HTML')});draft.sid=sid;oaudit(p.driver_id,sid,'Relevé émis',{mode:p.mode,revision:p.revision});return {statement_id:sid,already_created:false};
 }
 if(part==='transactions'&&path[2]==='void'){const t=find(localDemo.transactions,id);if(!d.reason?.trim())throw Error('Motif obligatoire.');if(t.voided_at)throw Error('Écriture déjà annulée.');t.voided_at=onow();t.void_reason=d.reason;const s=find(localDemo.statements,t.statement_id);oaudit(s.driver_id,s.id,'Écriture annulée',{transaction_id:id,amount_cents:t.amount_cents,reason:d.reason});return {ok:true}}
 if(part==='statements'){
  const raw=find(scoped(),id),s=osummary(raw);
  if(!path[2])return {statement:s,print_snapshot:raw.print_snapshot||null,lines:localDemo.lines.filter(l=>l.statement_id===id),transactions:localDemo.transactions.filter(t=>t.statement_id===id).reverse(),audit:localDemo.audit.filter(a=>a.statement_id===id)};
  if(s.cancelled_at)throw Error('Relevé annulé.');
  if(path[2]==='cancel'){if(!d.reason?.trim())throw Error('Motif obligatoire.');if(localDemo.transactions.some(t=>t.statement_id===id&&!t.voided_at))throw Error('Annulez d’abord les écritures actives.');raw.cancelled_at=onow();raw.cancel_reason=d.reason;localDemo.lines.filter(l=>l.statement_id===id).forEach(l=>l.active=0);oaudit(s.driver_id,id,'Relevé annulé',{reason:d.reason});return {ok:true}}
  if(path[2]==='transactions'){const amount=ocent(d.amount),cash=d.kind==='cash',prior=localDemo.transactions.find(t=>t.request_key===d.request_key);if(prior){if(prior.statement_id!==id||prior.amount_cents!==amount||prior.reference!==d.reference||prior.kind!==d.kind)throw Error('Clé déjà utilisée.');return {already_recorded:true,transaction_id:prior.id}}if(!['cash','commission'].includes(d.kind)||!['Espèces','Virement','Chèque'].includes(d.method))throw Error('Flux ou mode invalide.');if(!amount||amount>s[cash?'cash_remaining_cents':'commission_remaining_cents'])throw Error('Montant invalide ou supérieur au solde.');if(!d.reference?.trim())throw Error('Référence obligatoire.');if(!d.paid_on||d.paid_on>financeDay())throw Error('Date invalide ou future.');if(localDemo.transactions.some(t=>t.statement_id===id&&t.kind===d.kind&&!t.voided_at&&t.reference.toLowerCase()===d.reference.toLowerCase()))throw Error('Référence déjà enregistrée.');const t={...d,id:oid(localDemo.transactions),statement_id:id,amount_cents:amount,created_at:onow(),actor_name:localUser.name,voided_at:null};localDemo.transactions.push(t);oaudit(s.driver_id,id,cash?'Remise COD enregistrée':'Commission payée',{transaction_id:t.id,amount_cents:amount,reference:d.reference});return {transaction_id:t.id,already_recorded:false}}
 }
 throw Error('Action non disponible dans le fichier HTML. Utilisez la version serveur.');
}
function ovalidateAnnouncement(d,updating){
 const fields=['title','body','kind','audience','active','position','link_kind','link_label','link_url',...(updating?['revision']:[])];if(Object.keys(d).sort().join(',')!==fields.sort().join(','))throw Error('Champs invalides.');
 for(const [key,max,required] of [['title',120,true],['body',900,true],['link_label',90,false],['link_url',1000,false]]){if(typeof d[key]!=='string'||d[key].trim().length>max||(required&&!d[key].trim()))throw Error('Champ invalide : '+key);d[key]=d[key].trim()}
 if(!['info','warning','important','banner'].includes(d.kind)||!['none','url','template'].includes(d.link_kind))throw Error('Présentation ou lien invalide.');
 if(!Array.isArray(d.audience)||!d.audience.length||d.audience.some(r=>!['admin','client','livreur'].includes(r))||new Set(d.audience).size!==d.audience.length)throw Error('Choisissez les espaces destinataires.');
 if(typeof d.active!=='boolean'||!Number.isInteger(d.position)||d.position<0||d.position>99)throw Error('Publication ou ordre invalide.');if(updating&&(!Number.isInteger(d.revision)||d.revision<1))throw Error('Version invalide.');
 if(d.link_kind==='none'){d.link_label='';d.link_url=''}else{if(!d.link_label)throw Error('Libellé du lien obligatoire.');if(d.link_kind==='template'){if(d.audience.includes('livreur'))throw Error('Le modèle Excel est réservé aux espaces Admin et Client.');d.link_url=''}else{let valid=false;try{const u=new URL(d.link_url);valid=u.protocol==='https:'&&!!u.hostname&&!u.username&&!u.password&&!/[\s\\]/.test(d.link_url)}catch{}if(!valid)throw Error('Lien HTTPS complet requis, sans identifiants.')}}
 const {revision,...v}=d;v.audience=['admin','client','livreur'].filter(r=>d.audience.includes(r));return v;
}
async function offlineApi(url,method='GET',data={}){
 const d=ocopy(data||{}),parts=url.split('/').filter(Boolean),type=parts[0].split('?')[0],id=Number(parts[1]);let result;
 if(url==='/public')return {cities:localDemo.cities.filter(c=>c.delivery),brand:'ORIENTAL24'};
 if(url==='/login'){localUser=localDemo.users.find(u=>u.email.toLowerCase()===d.email.toLowerCase()&&u.active);if(!localUser||d.password!=='Oriental24!Demo'){localUser=null;throw Error('Utilisez les boutons Admin, Client ou Livreur et les comptes de démonstration.')}return {ok:true}}
 if(url==='/logout'){localUser=null;return {ok:true}}
 if(url==='/register')throw Error('Pas de création de comptes réels dans ce HTML. Utilisez le bouton Client de démonstration.');
 if(!localUser)throw Error('Choisissez un espace de démonstration.');
 const linkedClaim=type==='logistics'&&parts[1]==='parcels'&&parts[3]==='tickets'&&parts.length===4&&method==='POST';
 if(type==='partner'&&parts[1]==='v1'){offlineUnavailable('API partenaires — version serveur');return}
 if(!linkedClaim&&method!=='GET'&&localUser.role!=='admin'&&!['parcels','tickets','requests','pickups','products','stock','scan','labels','profile','logout','partner-palettes'].includes(type))throw Error('Action réservée au mode Admin.');
 if(type==='bootstrap')result={user:localUser,csrf:'offline-demo',cities:localDemo.cities,users:localUser.role==='admin'?localDemo.users:[],hubs:['admin','agent'].includes(localUser.role)?(localDemo.ops_hubs||[]).map(h=>({...h,city:localDemo.cities.find(c=>c.id===h.city_id)?.name||''})):[] ,parcels:oparcels(),statuses:OFFLINE_SEED.statuses,status_policy:OFFLINE_SEED.status_policy,settings:localDemo.settings};
 else if(type==='clients'&&parts[2]==='tariffs'){
  requireAdmin();localDemo.client_tariffs=localDemo.client_tariffs||[];localDemo.client_tariff_audit=localDemo.client_tariff_audit||[];
  const cl=find(localDemo.users,id),cityId=Number(parts[3]);
  if(method==='GET')result={client:{id:cl.id,name:cl.name,company:cl.company,client_type:cl.client_type||'vendeur'},cities:localDemo.cities.map(ci=>{const t=localDemo.client_tariffs.find(t=>t.client_id===cl.id&&t.city_id===ci.id);return {city_id:ci.id,city:ci.name,default_fee:ci.fee,default_return_fee:ci.return_fee,fee:t?t.fee:null,return_fee:t?t.return_fee:null,updated_at:t?.updated_at||null,updated_by:t?ouser(t.actor_id).name:null}}),audit:localDemo.client_tariff_audit.filter(a=>a.client_id===cl.id).map(a=>({...a,city:localDemo.cities.find(c=>c.id===a.city_id)?.name||'',actor:ouser(a.actor_id).name})).reverse().slice(0,100)};
  else{const ov=localDemo.client_tariffs.find(t=>t.client_id===cl.id&&t.city_id===cityId),city=find(localDemo.cities,cityId),audit=(o,n)=>localDemo.client_tariff_audit.push({id:oid(localDemo.client_tariff_audit),client_id:cl.id,city_id:cityId,actor_id:localUser.id,old_fee:o?o.fee:city.fee,old_return_fee:o?o.return_fee:city.return_fee,new_fee:n?n.fee:null,new_return_fee:n?n.return_fee:null,created_at:onow()});
   if(method==='PUT'){const fee=Number(d.fee),ret=Number(d.return_fee);if(![fee,ret].every(v=>Number.isFinite(v)&&v>=0&&v<=10000))throw Error('Montant invalide (0 à 10 000 MAD).');if(ov&&ov.fee===fee&&ov.return_fee===ret)result={ok:true,changed:false};else{audit(ov,{fee,return_fee:ret});if(ov){ov.fee=fee;ov.return_fee=ret;ov.updated_at=onow()}else localDemo.client_tariffs.push({client_id:cl.id,city_id:cityId,fee,return_fee:ret,actor_id:localUser.id,created_at:onow(),updated_at:onow()});result={ok:true,changed:true}}}
   else if(method==='DELETE'){if(!ov)result={ok:true,changed:false};else{audit(ov,null);localDemo.client_tariffs=localDemo.client_tariffs.filter(t=>t!==ov);result={ok:true,changed:true}}}
   else throw Error('Méthode non disponible.')}
 }
 else if(type==='partner-api-keys'){
  requireAdmin();localDemo.partner_api_keys=localDemo.partner_api_keys||[];
  if(method==='GET')result={rows:localDemo.partner_api_keys.map(k=>({...k,client:ouser(k.client_id).name,company:ouser(k.client_id).company,client_type:ouser(k.client_id).client_type,creator:ouser(k.created_by).name})).reverse()};
  else if(parts[2]==='revoke'){const k=find(localDemo.partner_api_keys,id);if(k.revoked_at)result={ok:true,changed:false};else{k.revoked_at=onow();result={ok:true,changed:true}}}
  else{const cl=find(localDemo.users,d.client_id);if((cl.client_type||'vendeur')!=='societe_livraison'||cl.role!=='client')throw Error('Clés API réservées aux sociétés de livraison.');if(localDemo.partner_api_keys.some(k=>k.client_id===cl.id&&!k.revoked_at))throw Error('Cette société possède déjà une clé active.');const label=String(d.label||'').trim();if(!label||label.length>80)throw Error('Libellé obligatoire.');const kid=oid(localDemo.partner_api_keys);localDemo.partner_api_keys.push({id:kid,client_id:cl.id,label,created_by:localUser.id,created_at:onow(),last_used_at:null,revoked_at:null});result={ok:true,id:kid,key:'O24K-DEMO-'+financeKey().slice(0,32),company:cl.company||cl.name}}
 }
 else if(type==='alerts'&&method==='GET'){
  if(!['admin','agent'].includes(localUser.role))throw Error('Alertes réservées à Admin et aux agents.');
  oppInit();const st=k=>Math.max(0,Math.min(720,Number(localDemo.settings[k]??({alert_transit_hours:48,alert_partial_hours:24,alert_unassigned_hours:24})[k]))),own=h=>localUser.role==='agent'?h===localUser.agent_hub_id:true,age=ts=>Math.floor((Date.now()-new Date(ts).getTime())/36e5);
  const docs=localDemo.partner_palettes.filter(p=>own(p.destination_hub_id)),g=(kind,limit,title,items)=>({kind,limit,title,items:items.slice(0,100)});
  result={groups:[
   g('transit',st('alert_transit_hours'),'Palettes envoyées non arrivées',st('alert_transit_hours')?docs.filter(p=>p.status==='En transit'&&age(p.dispatched_at)>=st('alert_transit_hours')).map(p=>({document_id:p.id,reference:p.reference,company:p.client_name,hub:p.destination_name,age_hours:age(p.dispatched_at)})):[]),
   g('partial',st('alert_partial_hours'),'Réceptions partielles en attente',st('alert_partial_hours')?docs.filter(p=>p.status==='Partiellement reçu'&&age(p.dispatched_at)>=st('alert_partial_hours')).map(p=>({document_id:p.id,reference:p.reference,company:p.client_name,hub:p.destination_name,age_hours:age(p.dispatched_at)})):[]),
   g('unassigned',st('alert_unassigned_hours'),'Colis réceptionnés non affectés',st('alert_unassigned_hours')?localDemo.parcels.filter(p=>p.status==='Réceptionné'&&!p.driver_id&&own(p.current_hub_id)&&age(p.updated_at)>=st('alert_unassigned_hours')).map(p=>({parcel_id:p.id,tracking:p.tracking,company:ouser(p.client_id).company||ouser(p.client_id).name,hub:(localDemo.ops_hubs||[]).find(h=>h.id===p.current_hub_id)?.name||'',age_hours:age(p.updated_at)})):[]),
   g('incidents',0,'Incidents de réception ouverts',docs.flatMap(p=>(localDemo.pp_incidents||[]).filter(i=>i.document_id===p.id&&i.status!=='Traité').map(i=>({document_id:p.id,reference:p.reference,company:p.client_name,kind:i.kind}))))
  ]};
 }
 else if(type==='partner-palettes')result=offlinePartnerPalettes(url,method,d);
 else if(type==='logistics'&&parts[1]==='hubs'&&method==='POST'){requireAdmin();oppInit();const name=String(d.name||'').trim(),address=String(d.address||'').trim(),city=find(localDemo.cities,d.city_id);if(!name||name.length>100||!address||address.length>300)throw Error('Nom et adresse du hub requis.');if(localDemo.ops_hubs.some(h=>h.name.toLowerCase()===name.toLowerCase()))throw Error('Nom de hub déjà utilisé.');const hid=oid(localDemo.ops_hubs);localDemo.ops_hubs.push({id:hid,name,address,city_id:city.id,active:1,created_at:onow()});result={ok:true,id:hid}}
 else if(type==='drivers-workspace')result=offlineDriverWorkspace(url,method,d);
 else if(type==='announcements'){
  localDemo.announcements=localDemo.announcements||[];
  if(method==='GET'){if(parts[1]==='manage'){requireAdmin();result=localDemo.announcements}else result=localDemo.announcements.filter(n=>n.active&&n.audience.includes(localUser.role)).map(n=>Object.fromEntries(['id','title','body','kind','link_kind','link_label','link_url'].map(k=>[k,n[k]])));result=ocopy(result).sort((a,b)=>(a.position??localDemo.announcements.find(n=>n.id===a.id).position)-(b.position??localDemo.announcements.find(n=>n.id===b.id).position)||a.id-b.id)}
  else{
   requireAdmin();const updating=method==='PATCH'&&Number.isInteger(id)&&id>0;if(!updating&&!(method==='POST'&&parts[1]==='manage'))throw Error('Action invalide.');
   const values=ovalidateAnnouncement(d,updating),old=updating?find(localDemo.announcements,id):null;
   if(old&&d.revision!==old.revision)throw Error('Annonce modifiée. Fermez et actualisez avant de réessayer.');
   if(old&&Object.keys(values).every(k=>JSON.stringify(old[k])===JSON.stringify(values[k])))return {ok:true,changed:false,revision:old.revision};
   if(!old&&localDemo.announcements.length>=50)throw Error('Limite de 50 annonces.');
   if(values.active&&!old?.active&&localDemo.announcements.filter(n=>n.active).length>=10)throw Error('Dix annonces actives maximum.');
   const before=old?ocopy(old):null,n={...values,id:old?.id||oid(localDemo.announcements),revision:(old?.revision||0)+1,created_at:old?.created_at||onow(),updated_at:onow(),updated_by:localUser.id};
   if(old)Object.assign(old,n);else localDemo.announcements.push(n);localDemo.announcement_audit=localDemo.announcement_audit||[];localDemo.announcement_audit.push({announcement_id:n.id,actor_id:localUser.id,before,after:ocopy(n),created_at:onow()});result={ok:true,id:n.id,revision:n.revision};
  }
 }
 else if(linkedClaim){
  const p=find(oparcels(),Number(parts[2]));
  if(!claimCategories.includes(d.category||'Livraison')||typeof d.subject!=='string'||!d.subject.trim()||d.subject.trim().length>180||typeof d.body!=='string'||!d.body.trim()||d.body.trim().length>3000)throw Error('Sujet, catégorie et description valides requis.');
  if(!['Basse','Normale','Haute'].includes(d.priority||'Normale'))throw Error('Priorité invalide.');
  if(d.request_key!==undefined&&(typeof d.request_key!=='string'||! /^[A-Za-z0-9_-]{16,100}$/.test(d.request_key)))throw Error('Clé de requête invalide.');
  localDemo.claim_requests=localDemo.claim_requests||[];localDemo.claim_attachments=localDemo.claim_attachments||[];
  const fingerprint=JSON.stringify(d),prior=d.request_key&&localDemo.claim_requests.find(r=>r.user_id===localUser.id&&r.key===d.request_key);
  if(prior){if(prior.parcel_id!==p.id||prior.fingerprint!==fingerprint)throw Error('Clé utilisée pour une autre réclamation.');return {ok:true,id:prior.ticket_id,already_created:true}}
  if(!Array.isArray(d.attachments||[])||(d.attachments||[]).length>3)throw Error('Trois fichiers maximum.');let total=0;
  const attachments=(d.attachments||[]).map(f=>{if(typeof f.name!=='string'||!f.name||f.name.length>180||typeof f.content!=='string'||f.content.length>1400000)throw Error('Pièce jointe invalide.');let raw;try{raw=atob(f.content)}catch{throw Error('Pièce jointe invalide.')};total+=raw.length;if(!raw.length||total>1048576)throw Error('Pièces jointes : 1 Mo au total maximum.');const mime=raw.startsWith('%PDF-')&&raw.slice(-2048).includes('%%EOF')?'application/pdf':raw.startsWith('\x89PNG\r\n\x1a\n')?'image/png':raw.startsWith('\xff\xd8\xff')?'image/jpeg':null;if(!mime)throw Error('Formats acceptés : PDF, JPG ou PNG.');return {name:f.name.replace(/[\/\\]/g,'_'),content:f.content,mime,size:raw.length}});
  const tid=oid(localDemo.tickets);localDemo.tickets.push({id:tid,user_id:localUser.id,subject:d.subject.trim(),category:d.category||'Livraison',status:'Ouvert',created_at:onow(),parcel_id:p.id,tracking:p.tracking,priority:d.priority||'Normale',assigned_to:null,first_response_at:null});localDemo.messages.push({id:oid(localDemo.messages),ticket_id:tid,user_id:localUser.id,body:d.body.trim(),created_at:onow()});
  for(const f of attachments)localDemo.claim_attachments.push({...f,id:oid(localDemo.claim_attachments),ticket_id:tid,created_at:onow()});
  if(d.request_key)localDemo.claim_requests.push({user_id:localUser.id,key:d.request_key,fingerprint,parcel_id:p.id,ticket_id:tid});result={ok:true,id:tid};
 }
 else if(type==='claim-attachments'&&method==='GET'){const f=find(localDemo.claim_attachments||[],id);find(localDemo.tickets.filter(t=>oscope(t,'user_id')),f.ticket_id);result=f}
 else if(type==='logistics'&&parts[1]==='config'&&method==='GET')result={reasons:localDemo.followup_reasons,hubs:[]};
 else if(type==='parcels'&&parts[2]==='city'&&method==='PATCH'){
  requireAdmin();const shown=find(oparcels(),id),p=find(localDemo.parcels,id);
  if(Object.keys(d).sort().join(',')!=='city_id,revision'||!Number.isInteger(d.city_id)||d.city_id<=0)throw Error('Ville et version valides requises.');
  if(p.invoice_id||shown.financial_locked||p.operations_locked||oclosed(p))throw Error('Ville non modifiable : colis clôturé ou verrouillé.');
  if(!Number.isInteger(d.revision)||d.revision!==(p.ops_revision||0))throw Error('Le colis a changé. Actualisez la fiche.');
  const city=find(localDemo.cities,d.city_id);if(!city.delivery)throw Error('Choisissez une ville ouverte à la livraison.');
  if(city.id===p.city_id)result={ok:true,changed:false};
  else{const old=shown.city;p.city_id=city.id;p.updated_at=onow();p.ops_revision=(p.ops_revision||0)+1;oevent(p,'Ville de livraison modifiée : '+old+' → '+city.name+' · montant et frais du colis conservés · simulation HTML');result={ok:true,changed:true}}
 }
 else if(type==='parcels'&&parts[2]==='reason'&&method==='PATCH'){
  const shown=find(oparcels(),id),p=find(localDemo.parcels,id);
  if(localUser.role==='client')throw Error('Modification réservée à Admin / Livreur.');
  if(p.invoice_id||shown.financial_locked||p.operations_locked||(localUser.role==='livreur'&&['Livré','Retourné'].includes(p.status)))throw Error('Colis verrouillé ou clôturé.');
  if(!Number.isInteger(d.revision)||d.revision!==(p.ops_revision||0))throw Error('Le colis a changé. Rouvrez la note.');
  const reason=localDemo.followup_reasons.find(r=>r.code===d.reason_code&&r.active);
  if(d.reason_code!==null&&!reason)throw Error('Motif inconnu ou inactif.');
  if(d.reason_code===(p.reason_code||null))result={ok:true,changed:false};
  else{if(!d.reason_code&&p.status==='Programmé')throw Error('Un colis programmé doit conserver un motif.');const old=shown.reason_label||'Aucun motif';p.reason_code=d.reason_code;p.ops_revision=(p.ops_revision||0)+1;oevent(p,'Motif de suivi : '+old+' → '+(reason?.label||'Aucun motif')+' · simulation HTML');result={ok:true,changed:true}}
 }
 else if(type==='billing')result=obilling(url,method,d);
 else if(type==='client-finance'){requireAdmin();if(parts[1]==='invoices'&&parts[3]==='receipts')result=obclientAdd(Number(parts[2]),d);else if(parts[1]==='receipts'&&parts[3]==='void')result=obclientVoid(Number(parts[2]),d.reason);else throw Error('Action invalide.')}
 else if(type==='driver-finance')result=ofinance(url,method,d);
 else if(type==='imports')result=[];
 else if(type==='scan'){const found=oparcels().filter(p=>p.tracking.toUpperCase()===String(d.tracking).trim().toUpperCase());if(!found.length)throw Error('Référence introuvable dans cet espace.');if(found.length>1)throw Error('Référence identique chez plusieurs sociétés : ouvrez le bon colis via la recherche détaillée.');result=found[0];}
 else if(type==='labels'){result=d.ids.map(id=>{const p=find(oparcels(),id),codes=OFFLINE_CODES[p.tracking];if(!codes)throw Error('Les codes des nouveaux colis nécessitent la version serveur. Essayez un des 48 colis préchargés.');return {...p,...codes}})}
 else if(type==='parcels'){
  if(method==='POST'){if(localUser.role==='livreur')throw Error('Création réservée aux clients et à Admin.');const city=find(localDemo.cities,d.city_id);if(!city.delivery)throw Error('Ville fermée à la livraison.');const cid=localUser.role==='client'?localUser.id:Number(d.client_id),client=find(localDemo.users,cid),tracking=otracking(client,d.tracking);localDemo.client_tariffs=localDemo.client_tariffs||[];const ovt=localDemo.client_tariffs.find(t=>t.client_id===cid&&t.city_id===city.id);const p={...d,id:oid(localDemo.parcels),tracking,client_id:cid,city_id:city.id,driver_id:null,amount:ocent(d.amount)/100,fee:ovt?ovt.fee:city.fee,return_fee:ovt?ovt.return_fee:city.return_fee,status:'Créé',created_at:onow(),updated_at:onow(),invoice_id:null};find(localDemo.users,p.client_id);localDemo.parcels.unshift(p);oevent(p,'Colis ajouté dans la simulation locale');result={tracking:p.tracking}}
  else {const shown=find(oparcels(),id),p=find(localDemo.parcels,id);if(method==='PATCH'){if('revision' in d&&(!Number.isInteger(d.revision)||d.revision!==(p.ops_revision||0)))throw Error('Le colis a changé. Rouvrez sa liste d’états.');if(localUser.role==='client')throw Error('Action réservée à Admin / Livreur.');if(p.operations_locked)throw Error('Colis lié à une palette active : utilisez sa réception dédiée.');if(p.invoice_id||shown.financial_locked)throw Error('Colis verrouillé par un relevé.');if('driver_id'in d){requireAdmin();const did=Number(d.driver_id)||null;if(did!==p.driver_id&&p.status==='Reçu par le livreur'&&(!d.status||d.status==='Reçu par le livreur'))throw Error('Indiquez l’état réel de remise avant la réaffectation.');if(did&&!ouser(did).active)throw Error('Livreur inactif.');p.driver_id=did;}if(d.status){if(!OFFLINE_SEED.statuses.includes(d.status))throw Error('Statut invalide.');if(localUser.role==='livreur'){const next=OFFLINE_SEED.status_policy.driver_transitions;if(!(next[p.status]||[]).includes(d.status))throw Error('Transition non autorisée.')}if(d.status==='Reçu par le livreur'&&(!p.driver_id||!ouser(p.driver_id).active))throw Error('Affectez un livreur actif.');if(['Transit','Reçu par le livreur'].includes(d.status))p.current_hub_id=null;if(d.status==='Programmé'){if(!localDemo.followup_reasons.some(r=>r.active&&r.code===d.reason_code))throw Error('Choisissez un motif pour programmer.');if(!d.next_attempt_at||!Number.isFinite(new Date(d.next_attempt_at).getTime())||new Date(d.next_attempt_at)<=new Date())throw Error('Choisissez un rendez-vous futur.')}if(!['Livré','Refusé','Retourné'].includes(d.status))localDemo.driver_receipts=(localDemo.driver_receipts||[]).filter(r=>r.parcel_id!==p.id);p.status=d.status;p.note=d.note||p.note;p.reason_code=d.reason_code||null;p.next_attempt_at=d.status==='Programmé'?d.next_attempt_at:null;}p.ops_revision=(p.ops_revision||0)+1;p.updated_at=onow();oevent(p,d.note||'Mise à jour locale');}result={parcel:find(oparcels(),id),events:localDemo.events.filter(e=>e.parcel_id===id)}}
 }
 else if(type==='cities'){requireAdmin();const clean={name:d.name,region:d.region,delivery:!!d.delivery,pickup:!!d.pickup,fee:ocent(d.fee)/100,return_fee:ocent(d.return_fee)/100};if(localDemo.cities.some(c=>c.name.toLowerCase()===d.name.toLowerCase()&&c.id!==id))throw Error('Ville déjà présente.');if(id)Object.assign(find(localDemo.cities,id),clean);else localDemo.cities.push({...clean,id:oid(localDemo.cities)});result={ok:true}}
 else if(type==='settings'){requireAdmin();localDemo.settings.announcement=d.announcement;result={ok:true}}
 else if(type==='users'){requireAdmin();oppInit();const old=id?find(localDemo.users,id):null,role=old?.role||d.role;if(!['client','livreur','agent'].includes(role))throw Error('Rôle invalide.');if(role==='agent'){const hub=find(localDemo.ops_hubs,Number(d.agent_hub_id??old?.agent_hub_id));if(!hub||!hub.active)throw Error('Choisissez le hub de réception actif de cet agent.');}const kind=oclientType({client_type:d.client_type??old?.client_type??'vendeur'},role);const clean={name:d.name,phone:d.phone,company:d.company,active:d.active!==false,client_type:kind};if(role==='agent')clean.agent_hub_id=Number(d.agent_hub_id??old?.agent_hub_id);else delete clean.agent_hub_id;if(old){if(old.driver_archived&&clean.active)throw Error('Désarchivez le compte.');if(kind!==old.client_type&&localDemo.parcels.some(p=>p.client_id===old.id))throw Error('Type verrouillé : ce client possède déjà des colis.');if(kind!==old.client_type)localDemo.client_type_audit.push({user_id:old.id,actor_id:localUser.id,old_type:old.client_type,new_type:kind,created_at:onow()});Object.assign(old,clean);if(old.role==='livreur'){old.driver_blocked=Number(!clean.active);old.driver_revision=(old.driver_revision||1)+1}}else{if(localDemo.users.some(u=>u.email.toLowerCase()===String(d.email).toLowerCase()))throw Error('Adresse e-mail déjà utilisée.');const uid=oid(localDemo.users);localDemo.users.push({...clean,id:uid,email:d.email,role});if(role==='client')localDemo.client_type_audit.push({user_id:uid,actor_id:localUser.id,old_type:null,new_type:kind,created_at:onow()});}result={ok:true,id:old?.id||localDemo.users.at(-1).id}}
 else if(type==='profile'){if('client_type' in d)throw Error('Type géré par l’administration.');if(d.password)throw Error('Pas de changement de mot de passe réel dans la démo HTML.');Object.assign(localUser,{name:d.name,phone:d.phone,company:d.company});result={ok:true}}
 else if(type==='invoices'){
  if(localUser.role==='livreur')throw Error('Réservé à Admin / Client.');const rows=localDemo.invoices.filter(i=>oscope(i)).map(i=>({...i,client:ouser(i.client_id).name,company:ouser(i.client_id).company}));
  if(method==='POST'){requireAdmin();const ps=localDemo.parcels.filter(p=>p.client_id===Number(d.client_id)&&oclosed(p)&&!p.invoice_id);if(!ps.length)throw Error('Aucun colis clôturé non facturé.');const cod=ps.filter(p=>p.status==='Livré').reduce((a,p)=>a+ocent(p.amount),0),fees=ps.reduce((a,p)=>a+ocent(p.status==='Livré'?p.fee:p.return_fee),0),iid=oid(localDemo.invoices);localDemo.invoices.push({id:iid,client_id:Number(d.client_id),cod:cod/100,fees:fees/100,total:(cod-fees)/100,status:'À régler',created_at:onow()});ps.forEach(p=>{p.invoice_id=iid;oevent(p,'Relevé client local créé')});result={ok:true}}
  else if(id){const i=find(rows,id);if(method==='PATCH'){requireAdmin();const raw=find(localDemo.invoices,id),info=obclientInfo(raw);if(info.remaining_cents)obclientAdd(id,{amount:(info.remaining_cents/100).toFixed(2),method:'Autre',reference:'Déclaration manuelle locale '+financeKey().slice(0,8),payment_date:financeDay(),request_key:financeKey()});else obclientSync(raw)}result=obclientDetail(id)}else result=rows.map(obclientInfo);
 }
 else if(type==='tickets'){
  if(method==='POST'&&!id){const t={id:oid(localDemo.tickets),user_id:localUser.id,subject:d.subject,category:d.category,status:'Ouvert',created_at:onow()};localDemo.tickets.push(t);localDemo.messages.push({id:oid(localDemo.messages),ticket_id:t.id,user_id:localUser.id,body:d.body,created_at:onow()});result={ok:true}}
  else if(id){const t=find(localDemo.tickets.filter(t=>oscope(t,'user_id')),id);if(method==='PATCH'){requireAdmin();t.status=d.status;}if(method==='POST')localDemo.messages.push({id:oid(localDemo.messages),ticket_id:id,user_id:localUser.id,body:d.body,created_at:onow()});result={ticket:t,attachments:(localDemo.claim_attachments||[]).filter(f=>f.ticket_id===id).map(({content,...f})=>f),messages:localDemo.messages.filter(m=>m.ticket_id===id).map(m=>({...m,author:ouser(m.user_id).name,role:ouser(m.user_id).role}))}}
  else result=localDemo.tickets.filter(t=>oscope(t,'user_id')).map(t=>({...t,author:ouser(t.user_id).name})).reverse();
 }
 else if(type==='pickups'||type==='pallets'){
  const rows=localDemo[type];if(type==='pallets')requireAdmin();
  if(method==='POST'){if(type==='pickups'&&!find(localDemo.cities,d.city_id).pickup)throw Error('Ramassage indisponible.');rows.unshift({...d,id:oid(rows),city_id:Number(d.city_id),count:Number(d.count),user_id:localUser.id,code:'PAL-'+financeKey().slice(0,6).toUpperCase(),status:type==='pallets'?'En transit':'Demandé',created_at:onow()});result={ok:true}}
  else if(method==='PATCH'){requireAdmin();find(rows,id).status=type==='pallets'?'Réceptionnée':d.status;result={ok:true}}
  else result=rows.filter(r=>type==='pallets'||oscope(r,'user_id')).map(r=>({...r,client:ouser(r.user_id).name,city:localDemo.cities.find(c=>c.id===r.city_id)?.name}));
 }
 else if(type==='products'){
  const rows=localDemo.products.filter(p=>oscope(p));
  if(parts[2]==='movements'){const p=find(rows,id);if(method==='POST'){requireAdmin();const delta=Number(d.delta);if(!Number.isInteger(delta)||!delta||p.quantity+delta<0)throw Error('Quantité invalide ou stock insuffisant.');p.quantity+=delta;localDemo.movements.push({id:oid(localDemo.movements),product_id:id,actor_id:localUser.id,delta,note:d.note,created_at:onow()})}result=localDemo.movements.filter(m=>m.product_id===id).map(m=>({...m,actor:ouser(m.actor_id).name})).reverse()}
  else if(method==='POST'){localDemo.products.push({...d,id:oid(localDemo.products),client_id:localUser.role==='client'?localUser.id:Number(d.client_id),quantity:0,created_at:onow()});result={ok:true}}
  else result=rows.map(p=>({...p,company:ouser(p.client_id).company}));
 }
 else if(type==='stock'){
  if(parts[1]==='movements')result=localDemo.movements.filter(m=>oscope(find(localDemo.products,m.product_id))).map(m=>{const p=find(localDemo.products,m.product_id);return {...m,actor:ouser(m.actor_id).name,product:p.name,reference:p.reference,sku:p.reference,company:ouser(p.client_id).company}}).reverse();
  else if(method==='POST'){const p=find(localDemo.products.filter(p=>oscope(p)),d.product_id),q=Number(d.quantity);if(!Number.isInteger(q)||q<=0||!['Entrée','Sortie'].includes(d.kind))throw Error('Quantité ou type invalide.');localDemo.stock_requests.push({...d,id:oid(localDemo.stock_requests),product_id:p.id,client_id:p.client_id,created_by:localUser.id,quantity:q,status:'En attente',created_at:onow()});result={ok:true}}
  else if(method==='PATCH'){const r=find(localDemo.stock_requests.filter(r=>oscope(r)),parts[2]);if(r.status!=='En attente')throw Error('Demande déjà traitée.');if(localUser.role!=='admin'&&d.status!=='Annulée')requireAdmin();if(d.status==='Validée'){const p=find(localDemo.products,r.product_id),delta=r.kind==='Entrée'?r.quantity:-r.quantity;if(p.quantity+delta<0)throw Error('Stock insuffisant.');p.quantity+=delta;localDemo.movements.push({id:oid(localDemo.movements),product_id:p.id,actor_id:localUser.id,delta,note:r.reason,created_at:onow()})}r.status=d.status;r.admin_note=d.admin_note||'';r.processed_by=localUser.id;r.processed_at=onow();result={ok:true}}
  else result=localDemo.stock_requests.filter(r=>oscope(r)).map(r=>{const p=find(localDemo.products,r.product_id);return {...r,product:p.name,sku:p.reference,available:p.quantity,company:ouser(p.client_id).company,client:ouser(p.client_id).name,creator:ouser(r.created_by).name,processor:ouser(r.processed_by).name}}).reverse();
 }
 else if(type==='requests'){
  if(method==='POST'){const p=find(oparcels(),d.parcel_id);if(oclosed(p)||p.invoice_id)throw Error('Colis déjà clôturé.');localDemo.requests.push({...d,id:oid(localDemo.requests),parcel_id:p.id,user_id:localUser.id,amount:ocent(d.amount)/100,status:'En attente',created_at:onow()});result={ok:true}}
  else if(method==='PATCH'){requireAdmin();const r=find(localDemo.requests,id),p=find(localDemo.parcels,r.parcel_id);if(r.status!=='En attente')throw Error('Demande déjà traitée.');if(d.status==='Acceptée'){if(oclosed(p)||p.invoice_id)throw Error('Colis déjà clôturé.');p.amount=r.amount;p.updated_at=onow()}r.status=d.status;oevent(p,'Demande de prix '+d.status);result={ok:true}}
  else result=localDemo.requests.filter(r=>oscope(r,'user_id')).map(r=>({...r,tracking:find(localDemo.parcels,r.parcel_id).tracking,old_amount:find(localDemo.parcels,r.parcel_id).amount,author:ouser(r.user_id).name}));
 }
 else throw Error('Cette opération nécessite la version serveur. Elle n’est pas exécutée par le fichier HTML.');
 if(method!=='GET')opersist();return ocopy(result||{ok:true});
}
api=offlineApi;
uploadApi=async()=>{throw Error('Import Excel/CSV disponible dans la version serveur uniquement. Aucun fichier transmis.')};
function offlineUnavailable(title){modal(title,`<div class="form-hint">Cette fonction utilise le serveur dans la version complète. Le fichier HTML fonctionne sans serveur et ne l’exécute pas.</div><p style="font-size:12px;line-height:1.9;margin-top:18px">Vous pouvez ici tester les trois espaces, créer des colis, affecter un livreur, modifier les statuts, les villes et les tarifs, simuler les relevés et la caisse, les réclamations et le stock. Les QR des 48 colis d’exemple sont inclus.</p><p class="form-hint orange" style="margin-top:16px">Aucune authentification sécurisée, aucun paiement, aucune synchronisation. Données fictives seulement.</p>`)}
openImports=()=>offlineUnavailable('Import Excel / CSV — version serveur');
startScannerCamera=()=>offlineUnavailable('Caméra — version serveur');
function offlineInfo(){modal('Votre démo HTML, sans installation',`<div class="form-hint orange">Fichier autonome · Simulation locale · Aucune connexion au serveur</div><h3 style="margin:22px 0 10px">Comment essayer ?</h3><ol style="padding-left:20px;font-size:12px;line-height:2"><li>Utilisez les boutons Admin, Client ou Livreur dans la barre du haut.</li><li>Créez un colis, affectez-le à un livreur et testez son suivi.</li><li>Dans Paramètres, modifiez la couverture et les tarifs de démonstration.</li><li>Dans Caisse livreurs, configurez votre barème avant d’émettre un relevé.</li><li>Réinitialisez à tout moment pour retrouver les données fictives initiales.</li></ol><p style="margin-top:20px;font-size:12px;line-height:1.8">${localPersistence?'Les modifications sont conservées dans ce navigateur, si son stockage local reste disponible.':'Le stockage local est indisponible dans cet aperçu : les modifications restent uniquement dans l’onglet courant.'} Aucun partage entre appareils. Ce HTML contient toutes les données de démonstration et ne constitue pas une barrière de sécurité entre les rôles.</p><p class="form-hint" style="margin-top:18px">Sécurité v1.4 (sessions et protections serveur) et modules v1.3 (documents logistiques, tentatives structurées, préparation stock, règlements clients partiels, dossiers de comptes et notifications), import Excel/CSV et caméra : version serveur uniquement. Les codes des nouveaux colis nécessitent le serveur ; ceux des 48 colis d’exemple sont intégrés. Pour imprimer ou télécharger un CSV si l’aperçu le bloque, téléchargez ce HTML et ouvrez-le dans Chrome ou Edge.</p>`)}
async function offlineSwitch(role){closeModal();resetDriverFinance();filters={q:'',status:'',city:'',from:'',to:''};await demoLogin(role);window.scrollTo(0,0)}
function offlineReset(){modal('Réinitialiser la démo ?',`<p style="line-height:1.9;font-size:13px">Toutes les modifications effectuées dans ce fichier seront supprimées. Les données fictives de départ seront restaurées. La version serveur n’est pas concernée.</p><div class="form-actions"><button class="btn" onclick="closeModal()">Conserver mes essais</button><button class="btn primary" onclick="offlineConfirmReset()">Réinitialiser</button></div>`)}
async function offlineConfirmReset(){localDemo=ocopy(OFFLINE_SEED);opersist();await offlineSwitch('admin');toast('Données de démonstration restaurées')}
function offlineDownload(url){if(!localUser)return;let rows,name;if(url==='/api/export'){rows=[['Référence','Destinataire','Ville','COD MAD','Statut'],...oparcels().map(p=>[p.tracking,p.recipient,p.city,p.amount,p.status])];name='ORIENTAL24-colis-demo.csv'}else if(url==='/api/driver-finance/export'){if(localUser.role==='client')return;rows=[['Relevé','Livreur','COD MAD','Commission MAD','COD restant MAD','Commission restante MAD','Statut'],...localDemo.statements.filter(s=>oscope(s,'driver_id')).map(osummary).map(s=>[s.reference,s.driver_name,s.cod_cents/100,s.commission_cents/100,s.cash_remaining_cents/100,s.commission_remaining_cents/100,s.status])];name='ORIENTAL24-caisse-demo.csv'}else{offlineUnavailable('Téléchargement — version serveur');return}const csv='\ufeff'+rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(';')).join('\r\n');const link=document.createElement('a'),blob=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.href=blob;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(blob),1000)}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href');if(href==='/'||href==='/login'){e.preventDefault();closeModal();href==='/'?renderPublic():renderLogin();window.scrollTo(0,0)}else if(href?.startsWith('/api/')){e.preventDefault();offlineDownload(href)}},true);
window.fetch=async()=>{throw Error('La démo HTML ne fait aucun appel réseau. Utilisez la version serveur pour cette fonction.')};
renderPublic();
