/* Local driver workflow simulation. Not authentication or server synchronization. */
function oreturned(p){return !!(localDemo.driver_receipts||[]).find(r=>r.parcel_id===p.id&&r.driver_id===p.driver_id)}
function offlineDriverWorkspace(url,method,d){
 requireAdmin();localDemo.driver_receipts=localDemo.driver_receipts||[];localDemo.driver_workspace_audit=localDemo.driver_workspace_audit||[];localDemo.driver_scan_keys=localDemo.driver_scan_keys||[];
 const parts=url.split('/').filter(Boolean),uid=Number(parts[1]),action=parts[2];const drivers=localDemo.users.filter(u=>u.role==='livreur');for(const u of drivers){u.driver_revision=u.driver_revision||1;u.driver_blocked=u.driver_blocked||0;u.driver_archived=u.driver_archived||0;u.driver_city_id=u.driver_city_id||null;u.driver_address=u.driver_address||''}
 const pending=id=>localDemo.parcels.filter(p=>p.driver_id===id&&p.status!=='Livré'&&!oreturned(p));const audit=(action,details={},pid=null)=>localDemo.driver_workspace_audit.unshift({id:oid(localDemo.driver_workspace_audit),driver_id:uid,actor:localUser.name,actor_id:localUser.id,action,details,parcel_id:pid,created_at:onow()});
 if(parts.length===1)return drivers.map(u=>({...u,outstanding:pending(u.id).length,delivered:localDemo.parcels.filter(p=>p.driver_id===u.id&&p.status==='Livré').length}));const u=find(drivers,uid);const revision=expected=>{if(!Number.isInteger(d.revision)||d.revision!==expected)throw Error('Données modifiées. Actualisez avant de confirmer.')};
 if(!action){if(method==='GET')return {driver:u,parcels:oparcels().filter(p=>p.driver_id===uid&&!p.driver_returned),audit:localDemo.driver_workspace_audit.filter(a=>a.driver_id===uid).slice(0,200)};
  revision(u.driver_revision);if(typeof d.name!=='string'||!d.name.trim()||d.name.length>120||typeof d.phone!=='string'||!/^\+?[0-9]{9,15}$/.test(d.phone.replace(/[ ()-]/g,''))||typeof d.address!=='string'||d.address.length>500)throw Error('Nom, téléphone ou adresse invalide.');if(d.city_id!==null&&!localDemo.cities.some(c=>c.id===d.city_id))throw Error('Ville invalide.');if(d.password)throw Error('La réinitialisation du mot de passe nécessite le serveur. Le HTML utilise les comptes de démonstration.');Object.assign(u,{name:d.name.trim(),phone:d.phone,driver_city_id:d.city_id,driver_address:d.address,driver_revision:u.driver_revision+1});audit('informations modifiées');return {ok:true};
 }
 if(action==='access'){revision(u.driver_revision);if(typeof d.reason!=='string'||!d.reason.trim()||d.reason.length>300)throw Error('Motif obligatoire, 300 caractères maximum.');if(!['block','unblock','archive','restore'].includes(d.action))throw Error('Action invalide.');if(d.action==='archive'&&pending(uid).length)throw Error('Récupérez les colis non livrés avant l’archivage.');if(d.action==='block')u.driver_blocked=1;if(d.action==='unblock')u.driver_blocked=0;if(d.action==='archive')u.driver_archived=1;if(d.action==='restore')u.driver_archived=0;u.active=Number(!u.driver_blocked&&!u.driver_archived);u.driver_revision++;audit(d.action,{reason:d.reason});return {ok:true};}
 const check=p=>{if(!['assign','receive'].includes(d.mode))throw Error('Mode invalide.');const receipt=localDemo.driver_receipts.find(r=>r.parcel_id===p.id);if(d.mode==='receive'&&receipt?.driver_id===uid&&[null,uid].includes(p.driver_id))return true;if(p.operations_locked)throw Error('Document actif : utilisez la réception dédiée.');if(d.mode==='assign'&&(localDemo.pp_incidents||[]).some(i=>i.parcel_id===p.id&&i.kind==='damaged'&&i.resolution!=='release'))throw Error('Colis réceptionné endommagé : incident à traiter avant affectation.');const locked=p.invoice_id||localDemo.lines.some(l=>l.parcel_id===p.id&&l.active);if(d.mode==='assign'){if(!u.active||u.driver_archived)throw Error('Livreur bloqué ou archivé.');if(oclosed(p)||locked)throw Error('Colis clôturé ou verrouillé.');if(p.driver_id&&p.driver_id!==uid)throw Error('Récupérez le colis auprès du livreur actuel.');return p.driver_id===uid&&['Reçu par le livreur','En livraison'].includes(p.status)&&!receipt}if(p.driver_id!==uid)throw Error('Ce colis n’est pas affecté à ce livreur.');if(p.status==='Livré')throw Error('Colis Livré : il reste associé au livreur.');if(!oclosed(p)&&locked)throw Error('Colis verrouillé financièrement.');return false};
 if(action==='scan-preview'){const found=localDemo.parcels.filter(p=>p.tracking.toUpperCase()===String(d.tracking).trim().toUpperCase());if(!found.length)throw Error('Référence introuvable.');if(found.length>1)throw Error('Référence identique chez plusieurs sociétés : ouvrez le bon colis via la recherche.');const p=found[0];return {parcel:find(oparcels(),p.id),already:!!check(p)}}
 if(action!=='scan'||d.confirmed!==true||!Number.isInteger(d.parcel_id)||! /^[A-Za-z0-9_-]{16,100}$/.test(d.request_key||''))throw Error('Confirmation de remise et clé valides requises.');const fingerprint=JSON.stringify([uid,d]),prior=localDemo.driver_scan_keys.find(k=>k.actor_id===localUser.id&&k.key===d.request_key);if(prior){if(prior.fingerprint!==fingerprint)throw Error('Clé déjà utilisée.');return {...prior.result,replayed:true}}
 if(d.hub_id!==null)throw Error('La gestion des hubs nécessite le serveur.');const p=find(localDemo.parcels,d.parcel_id),already=check(p);revision(p.ops_revision||0);
 if(!already){const before={status:p.status,driver_id:p.driver_id,reason_code:p.reason_code,next_attempt_at:p.next_attempt_at};if(d.mode==='assign'){Object.assign(p,{driver_id:uid,status:'Reçu par le livreur',current_hub_id:null,reason_code:null,next_attempt_at:null,updated_at:onow()});localDemo.driver_receipts=localDemo.driver_receipts.filter(r=>r.parcel_id!==p.id)}else{if(!oclosed(p))Object.assign(p,{driver_id:null,status:'Réceptionné',current_hub_id:null,reason_code:null,next_attempt_at:null,updated_at:onow()});p.current_hub_id=null;localDemo.driver_receipts=localDemo.driver_receipts.filter(r=>r.parcel_id!==p.id);localDemo.driver_receipts.push({parcel_id:p.id,driver_id:uid,received_at:onow(),hub_id:null})}p.ops_revision=(p.ops_revision||0)+1;audit(d.mode,{before},p.id);oevent(p,d.mode==='assign'?'Remise physique au livreur : '+u.name:'Récupéré physiquement à l’agence auprès de '+u.name+' · retiré de sa tournée')}
 const result={ok:true,already:!!already,parcel_id:p.id,mode:d.mode};localDemo.driver_scan_keys.push({actor_id:localUser.id,key:d.request_key,fingerprint,result});return result;
}
