/* Local partner-palette simulation: no server synchronization or security boundary. */
function oppInit(){localDemo.partner_palettes=localDemo.partner_palettes||[];localDemo.partner_palette_keys=localDemo.partner_palette_keys||[];localDemo.ops_hubs=localDemo.ops_hubs||[];localDemo.pp_incidents=localDemo.pp_incidents||[]}
function offlinePartnerPalettes(url,method,d){
 oppInit();if(!ppAccess(localUser))throw Error('Palettes réservées aux sociétés de livraison et à Admin.');
 const backup=method==='GET'?null:ocopy(localDemo),uid=localUser.id;
 try{return oppRoute(url,method,d)}catch(e){if(backup){localDemo=backup;localUser=localDemo.users.find(u=>u.id===uid)}throw e}
}
function oppRoute(url,method,d){
 const uri=new URL(url,'https://local.test'),parts=uri.pathname.split('/').filter(Boolean),id=Number(parts[1]),action=parts[2],admin=localUser.role==='admin',agent=localUser.role==='agent';
 const cl=(cid,active=true)=>{const u=ouser(cid);if(u.role!=='client'||u.client_type!=='societe_livraison'||active&&!u.active)throw Error('Société de livraison active requise.');return u};
 const hub=hid=>{const h=localDemo.ops_hubs.find(h=>h.id===Number(hid)&&h.active);if(!h)throw Error('Hub de réception actif requis.');return h};
 const txt=(k,max,required=false)=>{const v=d[k]??'';if(typeof v!=='string'||v.trim().length>max||required&&!v.trim())throw Error('Champ invalide : '+k);return v.trim()};
 const guard=(p,cid,did)=>{if(p.client_id!==cid)throw Error('Colis inaccessible pour cette société.');if(p.status!=='Créé'||p.driver_id||p.current_hub_id||p.invoice_id||localDemo.lines.some(l=>l.parcel_id===p.id&&l.active))throw Error('Uniquement des colis Créé, non reçus, non affectés et non facturés.');if(localDemo.partner_palettes.some(x=>x.lines.some(l=>l.parcel_id===p.id&&(l.received_at||l.active&&x.id!==did))))throw Error('Colis déjà réservé ou réceptionné.');if(p.operations_locked&&!localDemo.partner_palettes.some(x=>x.id===did&&x.lines.some(l=>l.parcel_id===p.id&&l.active)))throw Error('Document actif.')};
 const format=raw=>{const lines=raw.lines.map(l=>({...l,phone:find(localDemo.parcels,l.parcel_id).phone,current_status:find(localDemo.parcels,l.parcel_id).status})),received=lines.filter(l=>l.received_at).length;return {...ocopy(raw),lines,count:lines.length,received,remaining:lines.length-received}};
 if(parts[1]==='config')return {hubs:localDemo.ops_hubs.filter(h=>h.active&&(!agent||h.id===localUser.agent_hub_id)).map(h=>({...h,city:find(localDemo.cities,h.city_id).name})),companies:admin?localDemo.users.filter(u=>u.role==='client'&&u.client_type==='societe_livraison'&&u.active):[]};
 if(parts[1]==='candidates'){const c=cl(admin?uri.searchParams.get('client_id'):localUser.id);return {client_id:c.id,rows:localDemo.parcels.filter(p=>{try{guard(p,c.id);return true}catch{return false}}).map(p=>({id:p.id,tracking:p.tracking,recipient:p.recipient,phone:p.phone,city:find(localDemo.cities,p.city_id).name}))}}
 if(parts.length===1&&method==='GET'){let rows=localDemo.partner_palettes.filter(p=>admin||p.client_id===localUser.id||(agent&&p.destination_hub_id===localUser.agent_hub_id));const q=(uri.searchParams.get('q')||'').toLowerCase(),state=uri.searchParams.get('state');if(state)rows=rows.filter(p=>p.status===state);if(q)rows=rows.filter(p=>[p.reference,p.partner_reference,p.client_name,...p.lines.map(l=>l.tracking)].some(v=>v.toLowerCase().includes(q)));rows=rows.sort((a,b)=>b.id-a.id);const size=[20,50,100].includes(Number(uri.searchParams.get('size')))?Number(uri.searchParams.get('size')):20,page=Math.min(Math.max(1,Number(uri.searchParams.get('page'))||1),Math.max(1,Math.ceil(rows.length/size)));return {rows:rows.slice((page-1)*size,page*size).map(format),total:rows.length,page,size}}
 const docRaw=id?localDemo.partner_palettes.find(p=>p.id===id):null;let doc=id&&docRaw&&(admin||docRaw.client_id===localUser.id||(agent&&docRaw.destination_hub_id===localUser.agent_hub_id))?docRaw:null;
 const refuse=(msg,details)=>{if(docRaw)docRaw.audit.unshift({id:docRaw.audit.length+1,actor:localUser.name,actor_id:localUser.id,action:'Réception refusée',details,created_at:onow()});throw Error(msg)};
 if(id&&!doc&&!['receive','receive-all'].includes(action))throw Error('Palette introuvable.');if(id&&method==='GET'&&parts[2]==='incidents')return {rows:localDemo.pp_incidents.filter(i=>i.document_id===doc.id).map(i=>({...i,photo:undefined,has_photo:!!i.photo,creator:ouser(i.created_by).name})).reverse(),damaged_holds:localDemo.pp_incidents.filter(i=>i.document_id===doc.id&&i.kind==='damaged'&&i.resolution!=='release').map(i=>i.parcel_id)};if(id&&method==='GET')return format(doc);
 if(method!=='POST')throw Error('Méthode non disponible.');const subAction=parts[2]==='incidents'&&parts[3];
 if(id&&['receive','receive-all'].includes(action)){
  if(!admin&&!agent)refuse('Réception physique réservée à Admin et aux agents de réception.',{reason:'Rôle non autorisé à la réception physique',actor_role:localUser.role,actor_hub_id:localUser.agent_hub_id??null});
  if(!doc)refuse('Palette introuvable pour votre hub.',{reason:'Agent rattaché à un autre hub',actor_hub_id:localUser.agent_hub_id??null,palette_hub_id:docRaw?docRaw.destination_hub_id:null});
 }
 if(['dispatch','cancel'].includes(action)&&agent)throw Error('Préparation réservée à la société ou à Admin.');if(id&&d.confirmed!==true&&!subAction)throw Error('Confirmation physique requise.');
 if(!subAction&&!/^[A-Za-z0-9_-]{20,80}$/.test(d.request_key||''))throw Error('Clé invalide.');const fp=JSON.stringify([id||null,action||'create',Object.fromEntries(Object.entries(d).sort(([a],[b])=>a.localeCompare(b)))]),prior=subAction?null:localDemo.partner_palette_keys.find(k=>k.actor_id===localUser.id&&k.key===d.request_key);if(prior){if(prior.fp!==fp)throw Error('Clé déjà utilisée.');return {...prior.result,replayed:true}}
 const audit=(action,details)=>doc.audit.unshift({id:doc.audit.length+1,actor:localUser.name,actor_id:localUser.id,action,details,created_at:onow()});
 const result=extra=>{const r={ok:true,id:doc.id,reference:doc.reference,revision:doc.revision,status:doc.status,...extra};localDemo.partner_palette_keys.push({actor_id:localUser.id,key:d.request_key,fp,result:r});return r};
 if(!id){if(agent)throw Error('Préparation réservée à la société ou à Admin.');const c=cl(admin?d.client_id:localUser.id),h=hub(d.destination_hub_id),ids=d.parcel_ids;if(!Array.isArray(ids)||!ids.length||ids.length>500||new Set(ids).size!==ids.length||ids.some(i=>!Number.isInteger(i)||i<=0))throw Error('Choisissez 1 à 500 colis distincts.');const ps=ids.map(i=>find(localDemo.parcels,i));ps.forEach(p=>guard(p,c.id));const next=oid(localDemo.partner_palettes);doc={id:next,reference:'PP-'+String(next).padStart(6,'0'),kind:'partner_palette',client_id:c.id,client_name:c.company||c.name,source_name:c.company||c.name,destination_hub_id:h.id,destination_name:h.name,partner_reference:txt('partner_reference',80),transport:txt('transport',120),note:txt('note',600),status:'Préparé',revision:1,created_at:onow(),audit:[],lines:ps.map((p,i)=>({id:i+1,parcel_id:p.id,tracking:p.tracking,recipient:p.recipient,city:find(localDemo.cities,p.city_id).name,initial_status:p.status,active:1,received_at:null,received_by:null,missing_at:null,missing_by:null}))};localDemo.partner_palettes.push(doc);ps.forEach(p=>p.operations_locked=true);audit('Palette préparée',{count:ps.length,parcel_ids:ids});return result({})}
 if(parts[2]==='incidents'&&!parts[3]){
  if(!admin&&!agent)throw Error('Écarts réservés à Admin et aux agents.');if(!['En transit','Partiellement reçu'].includes(doc.status))throw Error('Écarts uniquement avant clôture.');
  if(!['missing','extra','damaged'].includes(d.kind))throw Error('Type d’écart invalide.');if(typeof d.note!=='string'||!d.note.trim()||d.note.length>600)throw Error('Constat obligatoire.');
  const pend=doc.lines.filter(l=>!l.received_at&&!l.missing_at);let line=null,tracking=typeof d.tracking==='string'?d.tracking.trim():'';
  if(d.kind==='missing'){line=pend.find(l=>l.id===Number(d.line_id));if(!line)throw Error('Colis attendu introuvable. Actualisez.');tracking=line.tracking}
  if(d.kind==='damaged'){line=pend.find(l=>l.tracking.toLowerCase()===tracking.toLowerCase());if(!line)throw Error('Ce tracking n’est plus à recevoir. Actualisez.');if(!d.photo)throw Error('Photo obligatoire pour un colis endommagé.')}
  if(!tracking)throw Error('Tracking obligatoire.');
  const at=onow(),iid=oid(localDemo.pp_incidents),inc={id:iid,document_id:doc.id,line_id:line?line.id:null,parcel_id:line?line.parcel_id:(localDemo.parcels.find(p=>p.tracking.toLowerCase()===tracking.toLowerCase()&&p.client_id===doc.client_id)?.id||null),company_id:doc.client_id,hub_id:doc.destination_hub_id,kind:d.kind,tracking,note:d.note.trim(),photo:d.photo||null,status:'Ouvert',company_response:'',responded_at:null,resolution:'',resolution_note:'',resolved_at:null,created_by:localUser.id,created_at:at};
  localDemo.pp_incidents.push(inc);
  if(d.kind==='missing'){Object.assign(line,{active:0,missing_at:at,missing_by:localUser.id});find(localDemo.parcels,line.parcel_id).operations_locked=false}
  if(d.kind==='damaged'){Object.assign(line,{active:0,received_at:at,received_by:localUser.id});const pr=find(localDemo.parcels,line.parcel_id);Object.assign(pr,{status:'Réceptionné',current_hub_id:doc.destination_hub_id,operations_locked:false,ops_revision:(pr.ops_revision||0)+1,updated_at:at});oevent(pr,doc.reference+' · réceptionné ENDOMMAGÉ — affectation suspendue')}
  if(line&&!pend.find(l=>l===line))0;const left=pend.filter(l=>l!==line).length;if(line){doc.status=left?'Partiellement reçu':(doc.lines.some(l=>l.missing_at)?'Clôturé (écarts)':'Reçu');doc.revision++;if(!left)doc.completed_at=at}
  audit({missing:'Colis déclaré manquant',extra:'Colis imprévu constaté',damaged:'Colis reçu endommagé'}[d.kind],{incident_id:iid,tracking,note:d.note.trim()});
  return result({incident_id:iid,status:doc.status,remaining:left});
 }
 if(parts[2]==='incidents'&&parts[4]==='respond'){
  if(localUser.role!=='client'||doc.client_id!==localUser.id)throw Error('Réponse réservée à la société concernée.');const inc=find(localDemo.pp_incidents,Number(parts[3]));if(inc.document_id!==doc.id)throw Error('Incident introuvable.');
  if(typeof d.response!=='string'||!d.response.trim()||d.response.length>600)throw Error('Réponse obligatoire.');if(inc.company_response===d.response.trim())return {ok:true,changed:false};
  inc.company_response=d.response.trim();inc.responded_at=onow();inc.status='Réponse société';audit('Réponse de la société sur un incident',{incident_id:inc.id});return {ok:true,changed:true};
 }
 if(parts[2]==='incidents'&&parts[4]==='resolve'){
  if(!admin&&!agent)throw Error('Décision réservée à Admin et aux agents.');const inc=find(localDemo.pp_incidents,Number(parts[3]));if(inc.document_id!==doc.id)throw Error('Incident introuvable.');
  if(typeof d.note!=='string'||!d.note.trim()||d.note.length>600)throw Error('Décision motivée obligatoire.');
  if(inc.kind==='damaged'){if(!['release','hold'].includes(d.action))throw Error('Choix invalide.');if(inc.resolution===d.action)return {ok:true,changed:false};inc.resolution=d.action;if(d.action==='release')oevent(find(localDemo.parcels,inc.parcel_id),'Incident endommagé traité : colis débloqué — '+d.note.trim())}
  else{if(d.action!=='close')throw Error('Action invalide.');if(inc.status==='Traité')return {ok:true,changed:false};inc.resolution='closed'}
  inc.resolution_note=d.note.trim();inc.resolved_at=onow();inc.status='Traité';audit('Incident traité',{incident_id:inc.id,resolution:inc.resolution});return {ok:true,changed:true};
 }
 if(parts[2]==='close-gaps'){
  if(!admin&&!agent)throw Error('Clôture avec écarts réservée à Admin et aux agents.');if(!['En transit','Partiellement reçu'].includes(doc.status))throw Error('Seule une palette envoyée peut être clôturée.');
  const pend=doc.lines.filter(l=>!l.received_at&&!l.missing_at);if(d.expected_remaining!==pend.length||!pend.length)throw Error('Le nombre de colis restants a changé. Actualisez.');
  if(typeof d.reason!=='string'||!d.reason.trim()||d.reason.length>600)throw Error('Motif obligatoire.');const at=onow(),ids=[];
  pend.forEach(l=>{const iid=oid(localDemo.pp_incidents);ids.push(iid);localDemo.pp_incidents.push({id:iid,document_id:doc.id,line_id:l.id,parcel_id:l.parcel_id,company_id:doc.client_id,hub_id:doc.destination_hub_id,kind:'missing',tracking:l.tracking,note:d.reason.trim(),photo:null,status:'Ouvert',company_response:'',responded_at:null,resolution:'',resolution_note:'',resolved_at:null,created_by:localUser.id,created_at:at});Object.assign(l,{active:0,missing_at:at,missing_by:localUser.id});find(localDemo.parcels,l.parcel_id).operations_locked=false});
  doc.status='Clôturé (écarts)';doc.completed_at=at;doc.revision++;audit('Palette clôturée avec écarts',{reason:d.reason.trim(),missing_trackings:pend.map(l=>l.tracking),incident_ids:ids});
  return result({status:doc.status,missing:pend.length,incident_ids:ids});
 }
 if(!['dispatch','cancel','receive','receive-all'].includes(action))throw Error('Action inconnue.');let line;
 if(action==='receive'){const code=txt('tracking',80,true);line=doc.lines.find(l=>l.tracking.toLowerCase()===code.toLowerCase());if(!line)throw Error('Ce tracking ne figure pas dans cette palette.');if(line.received_at)return result({already_received:true,received:0})}
 if(!Number.isInteger(d.revision)||d.revision!==doc.revision)throw Error('Palette modifiée. Actualisez avant confirmation.');
 if(action==='dispatch'||action==='cancel'){if(doc.status!=='Préparé')throw Error('Seule une palette brouillon peut être envoyée ou annulée.');if(action==='cancel'){doc.cancel_reason=txt('reason',600,true);doc.status='Annulé';doc.lines.forEach(l=>{l.active=0;find(localDemo.parcels,l.parcel_id).operations_locked=false});audit('Palette annulée avant envoi',{reason:doc.cancel_reason})}else{cl(doc.client_id);hub(doc.destination_hub_id);doc.lines.forEach(l=>guard(find(localDemo.parcels,l.parcel_id),doc.client_id,doc.id));doc.status='En transit';doc.dispatched_at=onow();audit('Envoi palette déclaré',{count:doc.lines.length});doc.lines.forEach(l=>oevent(find(localDemo.parcels,l.parcel_id),doc.reference+' · envoi société déclaré, réception encore attendue'))}doc.revision++;return result({})}
 if(!['En transit','Partiellement reçu'].includes(doc.status))throw Error('Confirmez l’envoi avant réception.');hub(doc.destination_hub_id);const pending=doc.lines.filter(l=>!l.received_at&&!l.missing_at);if(action==='receive-all'&&d.expected_remaining!==pending.length)throw Error('Le nombre de colis restants a changé.');const received=action==='receive'?[line]:pending;received.forEach(l=>guard(find(localDemo.parcels,l.parcel_id),doc.client_id,doc.id));const at=onow();received.forEach(l=>{Object.assign(l,{active:0,received_at:at,received_by:localUser.id});const p=find(localDemo.parcels,l.parcel_id);Object.assign(p,{status:'Réceptionné',current_hub_id:doc.destination_hub_id,reason_code:null,next_attempt_at:null,operations_locked:false,ops_revision:(p.ops_revision||0)+1,updated_at:at});oevent(p,doc.reference+' · réception physique ORIENTAL24 à '+doc.destination_name)});doc.status=received.length===pending.length?(doc.lines.some(l=>l.missing_at)?'Clôturé (écarts)':'Reçu'):'Partiellement reçu';doc.completed_at=received.length===pending.length?at:null;doc.revision++;audit(action==='receive-all'?'Réception complète confirmée':'Colis scanné reçu',{count:received.length,trackings:received.map(l=>l.tracking),parcel_ids:received.map(l=>l.parcel_id)});return result({already_received:false,received:received.length});
}
